name: Deploy Production (FTP)


on:
  push:
    branches: [ master ]
    
  workflow_dispatch: # manual execution

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: npm install

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%YT%H:%M:%S'))"
          
      - name: 📂 FTP - Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: varhub.myxomopx.ru
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: dist/
          
