name: CI

# Controls when the action will run. 
on:
  repository_dispatch:
    types: [opened, deleted]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ver_${{ github.event.client_payload.version }}
