name: CI

# Controls when the action will run. 
on:
  repository_dispatch:
    types: [commutator-update]

  workflow_dispatch: # manual execution
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      
      - uses: MYXOMOPX/modify-pkg-json@1.0.1
        with:
          # Path to package.json
          target: ./package.json
          # Action to perform
          action: "set_dep_version"
          argument: "@varhub-games/commutator ^${{ github.event.client_payload.version }}"
      
      - name: Setup Git & Commit 
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Commutator update to v${{ github.event.client_payload.version }}"" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
